before_script:
  - docker info

build_image:
  script:
    - docker build -t hpxdock:16.04 .

#test:
#  before_script:
#  - /builds/proxy/hpx/tests/scripts/install.sh
#  - /builds/proxy/hpx/scripts/buildandrunDebug.sh
#  script:
#  - pytest /builds/proxy/hpx/tests -s
