variables:
  GIT_SSL_NO_VERIFY: "true"

test_esc:
  before_script:
  - mkdir -p /builds/proxy/esc/build
  - cd /builds/proxy/esc/build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_PROJECT_CONFIG=esc -DCMAKE_BUILD_TYPE=Debug ../src
  - make clean
  - make -j4
  - export PYTHONPATH=/builds/proxy/esc:$PYTHONPATH
  script:
  - pytest /builds/proxy/esc/tests -s

pull_esc:
  script:
  - mkdir ~/.ssh
  - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa
  - cd /builds/proxy/esc
  - git checkout develop
  - git pull
  - git push git@github.com:EnterpriseServiceChain/esc.git develop:master
