services:
  - name: "ubuntu:latest"
    entrypoint: ["/bin/sh", "-c"]
    command: ["/bin/echo",  "212.87.28.162  git.bioinfo.dev", ">>", "/etc/hosts"]

test:
  script:
  - cd scripts
  - ./buildandrunDebug.sh
