variables:
  GIT_SSL_NO_VERIFY: "true"

#test_esc:
#  before_script:
#  - mkdir -p /builds/proxy/hpx/build
#  - cd /builds/proxy/hpx/build
#  - cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_PROJECT_CONFIG=esc -DCMAKE_BUILD_TYPE=Debug /builds/proxy/hpx/src
#  - make clean
#  - make -j4
#  - export PYTHONPATH=/builds/proxy/hpx:$PYTHONPATH
#  script:
#  - pytest /builds/proxy/hpx/tests -s


pull_hpx:
  script:
  - cd /builds/proxy/hpx
  - git remote add github git@github.com:EnterpriseServiceChain/esc.git
  - git push github develop:master
