# Project language
language: cpp

# Allows use container-based infrastructure
sudo: false

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.cache/pip
  - $HOME/ads/bin
  
addons:
  apt:
    packages:
      - realpath
  sonarcloud:
    organization: "adshares-github"
    token:
      secure: "DFgzbLYNJN7cORCbBu0B+iH3Su3J+iy1R6ONKVGMDv7r+OJT6YokgH+j7FEVdDpNhCgdjGnYx0POjfP0FAjDJMmH6KkIi9zsAhJFMF4zez89H5dgLbuubDABC1WMnz+schlg3irNqqZPktF9PousGXCFH/jP94D3pofr1/LXKIYXtnX8vgadHOrWkUyxg/cR7ThBMltmjoYEXkhsOgMgUNS0QH2EFqb8+TScUE47T1hpfNRzRYmOxeLKsDG1Q8eraWtR9VBJNuS/jCrjwEMGURdhs3cVlRx79rnV8vTYhxKKzRPEi05mEaXOgqD7qhWMgef17LAOVVNgQob5fxYAxVZnHIEWP99bmYD6BSbqOuQudYxwmRseR81tGcmGq4dgfsOkyVW/cRLPuVAkw+XOb0Z5EnxqwXfg+1q1XAhugbAHGrl26kYLRxtU8W9Gx5AbQWAujUmI2myJ2Nvw3mrvIpU1QJSYC8HF8VYyjJD98AzfuZziuUBbo51Af8k6HFvqJvZu3jJHurADHoBlBMJMxr3m0zuXfmPZPzxaqjDbmlOBMgxkI3BYjj4qPg9V9X1ABon+Wnt5AJpkH+MKvc8A9j5mrVLrnFuXDpgBUmRmhqq//z73n8Km4Au0M5z4faYFAChbxLdqbSPg60MmxbYtBMjtiUoSImD2vRF+dq3nB+c="
    github_token:
      secure: "occVw21D0BqL4kNwcvirh3Dtdm3P8McXtqsJSrxDWkfmlrxVEJ/BeTglYAEjWq2UOsOxxa8Tbu6MSwdyEUJ6cljakyq2QPlljhHVmxNX0undlXbvQmYJVEhOgLqYkrHj74tSsYoRibFzQ+LRJENtG+Yn6/g/FAejZu7k6kqqF3wsNJZ3uMEkQTIUUxEd7yJ1llIFTr5VgSpOifxBdBQGKdJ8TivFnGpzapwdOsyGWDdjMmf0UKLcZtjz4A17Mj3lcHAOZZ9IHcX2IrRhY0Ahk2nIaRSV9Mdtl2U4lSKi0PICg4tM3sc5mpZFqxHwVpA2Qpo/StrXoYqjy/myxEaFBSao8p1Ujjgh3SOmX2wrt6FHmzx1oMenZm786PJdOnTwLCM6dzWkh7EnTYEeST545i0aek3ptXaiB0005e0SyEKQH8xiW+cu6b3sPrH0Wv+8G6nwMUTNam+dT7Y/ZOPNN87Gs57maQas5so30fjeQuQyMELde+/OlndyHcCrf1ICASqznvMTzp6gyL2aa7XBZwog7Zn3+8kG7+rIfjTM8xx/GCw6bDpRj1h8UjeDRa08Kky9dWhEBcBSAkWXuhd+/HRNyz8XU/5lCkGTxVZ4siI5Khstd60TpJ2TYFPXP1bzAviBmAlPzVwmeOGwObAFpngW3nrpJ2mynuOAPw2wPwc="
      
before_install:
  # CONST
  - export TEST_DIR=$HOME/adshares/ads-tests
  - export GENESIS_FILE=$TEST_DIR/qa/config/genesis/genesis-retrieve-funds.json
  - export BIN_DIR=$HOME/ads/bin
  - export DATA_DIR=$HOME/ads/data

install:
  # PIP
  - sudo pip install psutil
  # QA TESTS
  - git clone https://github.com/adshares/ads-tests.git $TEST_DIR
  - cd $TEST_DIR
  - git checkout -qf ads-67-test-with-local-binary
  # COMMON
  - export PATH="$HOME/ads/bin:$PATH"
  - cd $TRAVIS_BUILD_DIR

jobs:
  include:
    - stage: compile
      script:
        # C++14
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
        - sudo apt-get --allow-unauthenticated install -qq gcc-5 g++-5 cmake
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
        # ---
        - mkdir build
        - sudo ./scripts/compile.sh -R src
        - ./scripts/compile.sh -d -o build -c "-DCODE_COVERAGE=1" src
        - mkdir -p $BIN_DIR
        - cp build/esc/esc $BIN_DIR
        - cp build/escd/escd $BIN_DIR
        - export PATH="$BIN_DIR:$PATH"

    #- stage: test
    #  script:
    #    - mvn clean test -q -f pom-qa.xml -Ddir.data=$DATA_DIR -Dgenesis.file=$GENESIS_FILE -Dcucumber.options="--tags @transfer"
    - stage: test
      script:
        - ./scripts/ads_configure.py --data_dir=$DATA_DIR --client=$BIN_DIR/esc --daemon=$BIN_DIR/escd --interface=127.0.0.1 $GENESIS_FILE
        - ./scripts/ads_ctl.py --data=$DATA_DIR --init --wait start
        - cd $TEST_DIR
        - mvn clean test -q -f pom-qa.xml -Ddir.data=$DATA_DIR -Dgenesis.file=$GENESIS_FILE -Dcucumber.options="--tags @broadcast"
    #    - mvn clean test -q -f pom-qa.xml -Ddir.data=$DATA_DIR -Dgenesis.file=$GENESIS_FILE -Dcucumber.options="--tags @non_existent"
    #    - mvn clean test -q -f pom-qa.xml -Ddir.data=$DATA_DIR -Dgenesis.file=$GENESIS_FILE -Dcucumber.options="--tags @retrieve_funds"
    #- stage: test
    #  script:
    #    - mvn clean test -q -f pom-qa.xml -Ddir.data=$DATA_DIR -Dgenesis.file=$GENESIS_FILE -Dcucumber.options="--tags @account"
    #- stage: test
    #  script:
    #    - mvn clean test -q -f pom-qa.xml -Ddir.data=$DATA_DIR -Dgenesis.file=$GENESIS_FILE -Dcucumber.options="--tags @node"
    #- stage: test
    #  script:
    #    - mvn clean test -q -f pom-qa.xml -Ddir.data=$DATA_DIR -Dgenesis.file=$GENESIS_FILE -Dcucumber.options="--tags @status"

    # Sonar Qube
    #- stage: quality
    #  script: sonar-scanner

notifications:
  email: false
  slack:
    rooms:
      secure: "mqIPOES4flFkWinn6YIJSDEwu+p976Sw1oq9Xd9lxuV5OH/Ow29oNwRxqoWtYhguCZ3F7rxDuXwXw+Mqp5hUQiWqTMmhZK5JW0oWYdi8BIz7Gif4KimsrCOrunCErXsp2ATh4NTO2Mz4ufhKORKGIE0UlywB9v8qOgE8JrgwdXvkHKsUeCf2Q5y2O6KnXFULDyUPZ3PZ4B79eK/3jCrZsrMLKdPZmlzbhZGWj4dfq0SSt2jFQULSQk7fyFVPC6myFjJK0eiVtkJVbR8BDninFX/wlCGf5nyJGVz87D/YcpkrbIIPLuPPow3PH+/Mk8j5FueEhIUcObMeZJ+SdCZW/jmYGN4xM8UW4pRK1sozEDRl9lhBPaJBSdiYsAoi33/xyr/WCOswX56NvE0dbuN126fgvJImZ0zAP33W4bM6IR1aDxnbbR0Kz7du3gu4kg71zJiFBomB+7yBxFoAcrricfxkdunI8QJpc0R0ElxiXbGCnJX7MKfOTmRjMABOjxNzCMOopcgVRjeVndgXiSc2uvknrCXuX4iekBsRHfetKfj/a/nVAFr2Z5WEH6UgLXrWzv7liSRY4xaaOAav0B78tueurLmI6ihoidN8Rk39Lz9BcvTRqPNzwg7McO3tP2dnLUuNnAIGzxp2tgjP1pGEVlUytEA8TVTJkyIIdKWwbto="
    on_success: change
    on_failure: always